### ISSUE TITLE
[토의 요청] leetcode 말고도 타 사이트의 문제 정답 코드도 기여 가능하게 둘까요?

### ISSUE THREAD

**Issue by hojoon0205** [20-1-SKKU-OSS/2020-1-OSS-7#12]
당장 여러분들도 아실 것 같은 백준(https://acmicpc.net) 의 정답 코드도 기여 가능하게 두는 것에 대해서 어떻게 생각하시나요?

**Comment by donghee11** [comment]
저희 프로젝트 주제와 관련이 있기때문에 좋은 것 같습니다.

**Comment by ssupecial** [comment]
저도 좋다고 생각합니다.

**Comment by mistercoin818** [comment]
저도 괜찮다고 생각합니다.

**Comment by hojoon0205** [comment]
그럼 언어 폴더 바로 밑에 BOJ 라는 폴더를 만들고 그 안에 작업물을 넣는걸로 합시다.
혹시 백준 말고 타 사이트 문제도 기여하고 싶으시다면 그대로 폴더 만들어서 기여해도 될 것 같습니다.
