### ISSUE TITLE
README.md 수정해야 할 것 같습니다.

### ISSUE THREAD

**Issue by hojoon0205** [20-1-SKKU-OSS/2020-1-OSS-7#16]
다른 사람들이 우리 repo에 들어왔을 때 설명이 하나도 되어있지 않네요.

가장 필요한 요소가 홈페이지 주소, 우리 repo에 대한 설명이 최우선인것 같고, 조원 소개나 라이센스 명시 같은건 그 다음 우선순위가 될 것 같습니다.

저 말고 다른 누군가가 작성해주셨으면 합니다.

**Comment by donghee11** [comment]
우선 큰것들 작성해놓았습니다. PR 확인부탁드립니다.

**Comment by hojoon0205** [comment]
당장 필요한 사항들은 완료된 것 같습니다.
